### ISSUE TITLE
Spotibar's default configuration directory is incorrect

### ISSUE THREAD

**Issue by Hellx2** [conor-f/spotibar#22]
I was just setting up spotibar and was having issues, as I just pressed enter when I was given the prompts for where to put the configuration files, but it seems to have thought that `~/filename` was actually `~/~/filename` and so it attempts to place the files there and fails because the directory doesn't exist. The only way I could fix this was creating a directory called `~` and placing the configuration files there.

**Comment by conor-f** [comment]
Hey @Hellx2 

Thanks for reporting this. I have reproduced it locally with the steps you provided. I spent a half hour trying to fix this in a clean way, but to no avail.

I am planning on improving a few aspects of `spotibar` in the next few weeks, so I'll update this issue once I've cleaned up the config management issues like this.

**Comment by conor-f** [comment]
This should all be tidied up now :) Let me know if there's still any issues
