### ISSUE TITLE
Waybar Support

### ISSUE THREAD

**Issue by Hellx2** [conor-f/spotibar#23]
Is there any chance that waybar support could be added any time soon? I've been using Wayland for a while and was wondering if support for this could be engineered.

**Comment by conor-f** [comment]
Hey @Hellx2 

Yep - I'll be improving performance and adding docs for `waybar`/`sway` in the next week or so hopefully!

**Comment by conor-f** [comment]
Working on this now. I have the config all set up for Waybar now, just fixing #22 and then will update the install instructions.

**Comment by conor-f** [comment]
Closing as this is completed. Tested with Sway and Waybar.
