### ISSUE TITLE
no command registered

### ISSUE THREAD

**Issue by daglaroglou** [conor-f/spotibar#25]
i installed spotibar via pip but cant run spotibar as command, its not recognized. i use arch and polybar

**Comment by conor-f** [comment]
Did you get this resolved? At a guess it was just a `PATH`/env issue that was fixed after sourcing your `.bashrc` or `.zshrc` or starting a new terminal, but if not, I'm glad to help!

**Comment by daglaroglou** [comment]
i got it resolved but i dont remeber how
