### ISSUE TITLE
warning: egrep is obsolescent When running spotibar --is-live

### ISSUE THREAD

**Issue by averwhy** [conor-f/spotibar#27]
I get the following output when i run --is-live:
```
egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
True
```
I believe it messes up the polybar config because 'True' isn't the first output.

**Comment by averwhy** [comment]
Might be something else, but i could not get it to work with either ```
exec-if = [ $(spotibar --is-live 2>/dev/null) = "True" ]
```
or
```
exec-if = [ $(spotibar --is-live | grep -oP "True|False") = "True" ]
```

**Comment by conor-f** [comment]
Hey there, thanks for opening the issue.

This should be resolved with [this commit](https://github.com/conor-f/spotibar/commit/d3061e19810e86bbb9a9e24ac43e5ebc346b9985). If you run `pipx upgrade spotibar`, or however you've chosen to install it, you should see the fix in version 0.5.0.

Let me know if this works, and if so you can close this issue :)

**Comment by averwhy** [comment]
I successfully upgraded it and it looks to be working! Quick recommendation, it would be nice to be able to configure the result of --get-currently-playing, so I could have it say Artist - Song instead of Song by Artist. Thanks for the help though!

**Comment by conor-f** [comment]
Cool idea - How would you like to specify that option?

**Comment by averwhy** [comment]
The simplest option i can think of is having a `spotibar --get-playing-artist` and `spotibar --get-playing-song`
